[package]
name = "hunspell"
version = "0.1.2"
authors = ["Lipka Boldizsár <lipkab@zoho.com>"]
description = "Rust bindings to the Hunspell library"
keywords = ["spellcheck", "hunspell"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/lipk/hunspell-rust"
edition = "2018"

[dependencies]
hunspell-sys = { git = "https://github.com/brainlock/hunspell-sys.git", rev = "161db11f0b726cb2fd756e261015a5f9e7e0f71f" }
